config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :questions do
    resources :answers, shallow: true, only: %i[create update destroy]

    member do
      patch :choose_best_answer
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index
  resources :votes, only: %i[create destroy]
  resources :comments, only: :create
  resources :subscriptions, only: %i[create destroy]

  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :award, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :award, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :subscribe_author

  def subscription_of(user)
    subscriptions.find_by(user: user)
  end

  private

  def subscribe_author
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    save_and_render(@question)
  end

  def update
    @question.update(question_params)
    save_and_render(@question)
  end

  def destroy
    @question.destroy
    head :no_content
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: %i[name url])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  after_action :publish_question, only: :create

  load_and_authorize_resource

  def index
    @questions = Question.all
  end

  def show
    answer.links.build
    gon.user_id = current_user&.id
  end

  def new
    question.links.build
    question.build_award
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question was successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def destroy
    question.destroy
    flash[:notice] = 'Your question was successfully deleted.'

    redirect_to questions_path
  end

  def choose_best_answer
    @previous_best_answer = question.best_answer
    question.transaction do
      question.update!(best_answer: answer)
      question.award&.update!(user: answer.author)
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def answer
    @answer ||= params[:answer_id] ? Answer.with_attached_files.find(params[:answer_id]) : Answer.new
  end

  helper_method :question, :answer

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:id, :name, :url, :_destroy], award_attributes: [:title, :image])
  end

  def publish_question
    if question.persisted?
      ActionCable.server.broadcast(
        'questions',
        ApplicationController.render(
          partial: 'questions/sub_question',
          locals: { question: question }
        )
      )
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
.errors
  = render 'shared/errors', resource: question

= form_with model: question, local: local, html: local_assigns[:html] || {} do |f|
  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :body
    br
    = f.text_area :body
  .field
    = f.label :files
    br
    = f.file_field :files, multiple: true, direct_upload: true
  h3 Links
  #links
    = f.fields_for :links do |link|
      = render 'links/fields', f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/fields'
  h3 Award
  #award
    = f.fields_for :award do |a|
      .field
        = a.label :title, 'Award Title'
        = a.text_field :title
      .field
        = a.label :image
        = a.file_field :image, direct_upload: true
  = f.submit 'Ask'

app/views/questions/_question.html.slim
.question id="question-#{question.id}"
  .content
    h2= link_to question.title, question_path(question)
    p= question.body

    - if question.files.attached?
      h3 Files
      .files
        - question.files.each do |file|
          div id="attachment-#{file.id}"
            = link_to file.filename.to_s, url_for(file)
            - if can?(:destroy, file)
              = link_to 'Delete file', attachment_path(file), method: :delete, remote: true

    - if question.links.any?
      h3 Links
      .links
        = render question.links

  = render 'form', question: question, local: false, html: { hidden: true }

  .actions
    - if can?(:update, question)
      = link_to 'Edit', '#', class: 'edit-link', data: { question_id: question.id }
    - if can?(:destroy, question)
      = link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are you sure?' }

app/views/questions/_sub_question.html.slim
.question id="question-#{question.id}"
  .content
    h2= link_to question.title, question_path(question)
    p= question.body

    - if question.files.attached?
      h3 Files
      .files
        - question.files.each do |file|
          div id="attachment-#{file.id}"
            = link_to file.filename.to_s, url_for(file)

    - if question.links.any?
      h3 Links
      .links
        - question.links.each do |link|
          div id="link-#{link.id}"
            = link_to link.name, link.url, target: '_blank', rel: 'nofollow'

app/views/questions/choose_best_answer.js.erb
<% if @previous_best_answer.present? %>
  $('#answer-<%= @previous_best_answer.id %> .best-answer').hide()
<% end %>

$('#answer-<%= question.best_answer.id %> .best-answer').show()
$('#answer-<%= question.best_answer.id %>').prependTo('.answers')

app/views/questions/index.html.slim
h1 Questions

= link_to 'Ask question', new_question_path

.questions
  = render @questions

app/views/questions/new.html.slim
h1 New Question

= render 'form', question: question, local: true

app/views/questions/show.html.slim
.question-show id="question-#{question.id}" data-question-id="#{question.id}"
  h1= question.title
  p= question.body

  - if question.files.attached?
    h3 Files
    .files
      - question.files.each do |file|
        = link_to file.filename.to_s, url_for(file)

  - if question.links.any?
    h3 Links
    .links
      = render question.links

  - if question.award.present?
    .award
      h3= "Recieve #{question.award.title} award for the best answer!"
      = image_tag question.award.image, size:"100x100"

  .subscribing
    = render 'subscriptions/subscribing', question: question, subscription: question.subscription_of(current_user)

  h3 Comments
  .comments
    = render question.comments
  .new-comment
    h3 New comment
    - if can?(:create, Comment)
      = render 'comments/form', commentable: question
    - else
      p Sign in to comment questions

  = render 'votes/voting', votable: question, vote: question.vote_of(current_user)

.answers
  h2 Answers
  = render question.answers

.new-answer
  h2 New answer
  - if can?(:create, Answer)
    = render 'answers/form', answer: answer, model: [question, answer]
  - else
    p Sign in to answer questions

app/views/questions/update.js.erb
$('#question-<%= question.id %> .errors').html('<%= render 'shared/errors', resource: question %>')

<% if !question.errors.present? %>
  $('#question-<%= question.id %>').replaceWith('<%= j render question %>')
<% end %>