config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :questions do
    resources :answers, shallow: true, only: %i[create update destroy]

    member do
      patch :choose_best_answer
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index
  resources :votes, only: %i[create destroy]
  resources :comments, only: :create
  resources :subscriptions, only: %i[create destroy]

  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User'
  belongs_to :question

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  before_destroy :nullify_best, if: :best?
  after_create :send_update

  def best?
    id == question.best_answer_id
  end

  private

  def nullify_best
    question.update(best_answer: nil)
  end

  def send_update
    QuestionUpdatesJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  after_action :publish_answer, only: :create

  load_and_authorize_resource

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = question
    @answer.save
  end

  def update
    answer.update(answer_params)
  end

  def destroy
    answer.destroy
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer ||= Answer.with_attached_files.find(params[:id])
  end

  helper_method :question, :answer

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end

  def publish_answer
    if answer.persisted?
      answer_partial = ApplicationController.render(
        partial: 'answers/sub_answer',
        locals: { answer: answer }
      )
      data = { answer: answer_partial, user_id: current_user.id, question_author_id: answer.question.author.id }
      AnswersChannel.broadcast_to(question, data)
    end
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    render json: question.answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params)
    @answer.question = question
    save_and_render(@answer)
  end

  def update
    @answer.update(answer_params)
    save_and_render(@answer)
  end

  def destroy
    @answer.destroy
    head :no_content
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, links_attributes: %i[name url])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer id="answer-#{answer.id}"
  = tag.div class: 'best-answer', data: { answer_id: answer.id }, hidden: !answer.best?
    b The best answer!

  .content
    p= answer.body

    - if answer.files.attached?
      h3 Files
      .files
        - answer.files.each do |file|
          div id="attachment-#{file.id}"
            = link_to file.filename.to_s, url_for(file)
            - if can?(:destroy, file)
              = link_to 'Delete file', attachment_path(file), method: :delete, remote: true

    - if answer.links.any?
      h3 Links
      .links
        = render answer.links

    h3 Comments
    .comments
      = render answer.comments
    .new-comment
      h3 New comment
      - if can?(:create, Comment)
        = render 'comments/form', commentable: answer
      - else
        p Sign in to comment answers

  = render 'votes/voting', votable: answer, vote: answer.vote_of(current_user)

  = render 'answers/form', answer: answer, model: answer, html: { hidden: true }

  .actions
    - if can?(:update, answer)
      = link_to 'Edit', '#', class: 'edit-link', data: { answer_id: answer.id }
    - if can?(:destroy, answer)
      = link_to 'Delete', answer_path(answer), method: :delete, remote: true
    - if can?(:choose_best_answer, answer.question)
      = link_to 'Mark as best', choose_best_answer_question_path(answer.question, answer_id: answer), method: :patch, remote: true

app/views/answers/_form.html.slim
.errors
  = render 'shared/errors', resource: answer

= form_with model: model, local: false, html: local_assigns[:html] || {} do |f|
  .field
    = f.label :body
    br
    = f.text_area :body
  .field
    = f.label :files
    br
    = f.file_field :files, multiple: true, direct_upload: true
  h3 Links:
  #links
    = f.fields_for :links do |link|
      = render 'links/fields', f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/fields'
  = f.submit 'Answer'

app/views/answers/_sub_answer.html.slim
.answer id="answer-#{answer.id}"
  = tag.div class: 'best-answer', data: { answer_id: answer.id }, hidden: !answer.best?
    b The best answer!

  .content
    p= answer.body

    - if answer.files.attached?
      h3 Files
      .files
        - answer.files.each do |file|
          div id="attachment-#{file.id}"
            = link_to file.filename.to_s, url_for(file)

    - if answer.links.any?
      h3 Links:
      .links
        - answer.links.each do |link|
          div id="link-#{link.id}"
            = link_to link.name, link.url, target: '_blank', rel: 'nofollow'

    h3 Comments
    .comments
    .new-comment hidden="true"
      h3 New comment
      = render 'comments/form', commentable: answer

  .voting
    .rating
      p= "Rating: #{answer.rating}"
    .vote-links hidden="true"
      = vote_link 'Upvote', :upvote, answer
      br
      = vote_link 'Downvote', :downvote, answer

  .actions hidden="true"
    = link_to 'Mark as best', choose_best_answer_question_path(answer.question, answer_id: answer), method: :patch, remote: true

app/views/answers/create.js.erb
$('.new-answer .errors').html('<%= render 'shared/errors', resource: answer %>')

<% if answer.persisted? %>
  $('.answers').append('<%= j render answer %>')
  $('.new-answer #answer_body').val('')
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= answer.id %>').remove()

app/views/answers/update.js.erb
$('#answer-<%= answer.id %> .errors').html('<%= render 'shared/errors', resource: answer %>')

<% if !answer.errors.present? %>
  $('#answer-<%= answer.id %>').replaceWith('<%= j render answer %>')
<% end %>